version: '3'

services:
  djangoapp:
    build:
      context: ./django
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
    env_file:
      - ./django/django_env
    command: python manage.py runserver 0.0.0.0:8000
    #command: gunicorn --bind 0.0.0.0:8000 app.wsgi
    volumes:
      - ~/docker/django/backend:/backend
      - ./ssh-keys:/root/.ssh
    networks:
      - nginx_network
      - db_network
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./django/backend/media:/opt/django/media
      - ./django/backend/static:/opt/django/static
    depends_on:
      - djangoapp
    networks:
      - nginx_network
  postgres:
     image: postgres:latest
     env_file:
       - ./postgres/config/db/postgres_env
     networks:
       - db_network
     volumes:
       - ./postgres/data:/var/lib/postgresql/data
networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge


