version: '3'

services:
  djangoapp:
    build: ./django/.
    env_file:
      - ./django/django_env
    volumes:
      - ./django/app:/backend/app
      - ./django/media:/backend/media
      - ./django/static:/backend/static
    networks:
      - nginx_network
      - db_network
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./django/media:/opt/django/media
      - ./django/static:/opt/django/static
    depends_on:
      - djangoapp
    networks:
      - nginx_network
  postgres:
     image: postgres:latest
     env_file:
       - ./postgres/config/db/postgres_env
     networks:
       - db_network
     volumes:
       - ./postgres/data:/var/lib/postgresql/data
networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge


